"""fix fk loop

Revision ID: 2f7dc2ad20f5
Revises: a263f5416f43
Create Date: 2026-09-18 18:41:31.696358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7dc2ad20f5'
down_revision: Union[str, Sequence[str], None] = 'a263f5416f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invoices_transaction_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'transaction_id')
    op.drop_constraint(op.f('payments_subscription_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_subscription_id_fkey'), 'payments', 'subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
    op.add_column('invoices', sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('invoices_transaction_id_fkey'), 'invoices', 'transactions', ['transaction_id'], ['id'])
    # ### end Alembic commands ###
