"""add pending status to subscription and relation payments to subscription

Revision ID: a263f5416f43
Revises: b3c0f67763a5
Create Date: 2026-09-11 12:21:42.466019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a263f5416f43'
down_revision: Union[str, Sequence[str], None] = 'b3c0f67763a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('subscription_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_column('payments', 'subscription_id')
    # ### end Alembic commands ###
